### ISSUE TITLE
java.lang.NullPointerException when call  tournament.getName(locale) 

### ISSUE THREAD

**Issue by OleksandrKorol** [sportradar/UnifiedOddsSdkJava#13]
Hi. When I call method tournament.**getName**(locale), or tournament.**getScheduledTime**() or tournament.**getScheduledEndTime**(),  I get

`StackTrace

java.lang.NullPointerException
	at com.sportradar.unifiedodds.sdk.caching.impl.ci.TournamentCIImpl.lambda$internalMerge$11(TournamentCIImpl.java:627)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.sportradar.unifiedodds.sdk.caching.impl.ci.TournamentCIImpl.internalMerge(TournamentCIImpl.java:627)
	at com.sportradar.unifiedodds.sdk.caching.impl.ci.TournamentCIImpl.merge(TournamentCIImpl.java:579)
	at com.sportradar.unifiedodds.sdk.caching.impl.SportEventCacheImpl.storeTournamentInfoEndpoint(SportEventCacheImpl.java:627)
	at com.sportradar.unifiedodds.sdk.caching.impl.SportEventCacheImpl.onTournamentInfoEndpointFetched(SportEventCacheImpl.java:299)
	at com.sportradar.unifiedodds.sdk.caching.impl.DataRouterImpl.lambda$onSummaryFetched$0(DataRouterImpl.java:45)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.sportradar.unifiedodds.sdk.caching.impl.DataRouterImpl.onSummaryFetched(DataRouterImpl.java:45)
	at com.sportradar.unifiedodds.sdk.caching.impl.DataRouterManagerImpl.requestSummaryEndpoint(DataRouterManagerImpl.java:342)
	at com.sportradar.unifiedodds.sdk.caching.impl.ci.TournamentCIImpl.lambda$requestMissingTournamentData$13(TournamentCIImpl.java:765)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.sportradar.unifiedodds.sdk.caching.impl.ci.TournamentCIImpl.requestMissingTournamentData(TournamentCIImpl.java:763)
	at com.sportradar.unifiedodds.sdk.caching.impl.ci.TournamentCIImpl.getNames(TournamentCIImpl.java:498)
	at com.sportradar.unifiedodds.sdk.impl.entities.TournamentImpl.getName(TournamentImpl.java:97)
	at com.egt.betradaradapter.service.processor.helpers.EventHelper.getTournament(EventHelper.java:126)
	at com.egt.betradaradapter.service.processor.helpers.EventHelper.fillEventNonNullFields(EventHelper.java:82)
	at com.egt.betradaradapter.service.processor.helpers.EventHelper.create(EventHelper.java:37)
	at com.egt.betradaradapter.service.processor.SportEventManager.prepareOptionalEventWithOdds(SportEventManager.java:176)
	at com.egt.betradaradapter.service.processor.SportEventManager.onOddsChange(SportEventManager.java:51)
	at jdk.internal.reflect.GeneratedMethodAccessor337.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:782)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at com.egt.betradaradapter.configuration.tracing.TracerService.produceTrace(TracerService.java:46)
	at jdk.internal.reflect.GeneratedMethodAccessor323.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.egt.betradaradapter.service.processor.SportEventManager$$EnhancerBySpringCGLIB$$3a666a3a.onOddsChange(<generated>)
	at com.egt.betradaradapter.service.processor.SportEventAdapter.onOddsChange(SportEventAdapter.java:30)
	at com.egt.betradaradapter.service.processor.SportEventAdapter$$FastClassBySpringCGLIB$$86657e17.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at com.egt.betradaradapter.configuration.tracing.TracerService.produceTrace(TracerService.java:46)
	at jdk.internal.reflect.GeneratedMethodAccessor323.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.egt.betradaradapter.service.processor.SportEventAdapter$$EnhancerBySpringCGLIB$$2d117a60.onOddsChange(<generated>)
	at com.egt.betradaradapter.service.FeedMessageListener.onOddsChange(FeedMessageListener.java:60)
	at com.egt.betradaradapter.service.FeedMessageListener$$FastClassBySpringCGLIB$$ccd581e7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at io.micrometer.core.aop.TimedAspect.processWithTimer(TimedAspect.java:119)
	at io.micrometer.core.aop.TimedAspect.timedMethod(TimedAspect.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor332.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at com.egt.betradaradapter.configuration.tracing.TracerService.produceTrace(TracerService.java:46)
	at jdk.internal.reflect.GeneratedMethodAccessor323.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.egt.betradaradapter.service.FeedMessageListener$$EnhancerBySpringCGLIB$$a4b508d8.onOddsChange(<generated>)
	at com.sportradar.unifiedodds.sdk.impl.OddsFeedSessionImpl.lambda$processMessage$0(OddsFeedSessionImpl.java:208)
	at com.sportradar.unifiedodds.sdk.impl.OddsFeedSessionImpl.checkUserException(OddsFeedSessionImpl.java:389)
	at com.sportradar.unifiedodds.sdk.impl.OddsFeedSessionImpl.processMessage(OddsFeedSessionImpl.java:208)
	at com.sportradar.unifiedodds.sdk.impl.processing.pipeline.CacheMessageProcessor.processMessage(CacheMessageProcessor.java:96)
	at com.sportradar.unifiedodds.sdk.impl.processing.pipeline.CompositeMessageProcessor.processMessage(CompositeMessageProcessor.java:103)
	at com.sportradar.unifiedodds.sdk.impl.OddsFeedSessionImpl.onMessageReceived(OddsFeedSessionImpl.java:150)
	at com.sportradar.unifiedodds.sdk.impl.ChannelMessageConsumerImpl.onMessageReceived(ChannelMessageConsumerImpl.java:201)
	at com.sportradar.unifiedodds.sdk.impl.RabbitMqChannelImpl$1.handleDelivery(RabbitMqChannelImpl.java:136)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)`

version sdk: 2.0.43.0

**Comment by dhrovat** [comment]
Hi,

this is a known bug, already fixed, just waiting to be published.

David
