### ISSUE TITLE
The SDK depends on a very old version of amqp-client 

### ISSUE THREAD

**Issue by jbx1** [sportradar/UnifiedOddsSdkJava#18]
The SDK depends on a very old version of the amqp-client, 3.6.0 which was released in Dec 2015, almost 6 years ago. 
There were over 60 versions released since then, and it is now on version 5.13.1.

Apart from being very old (it is not even supported any more), this creates a problem when using the SDK within a Spring Boot application (which is how most Java applications are written these days), because it also natively supports RabbitMQ but includes a later version (5.12). While this actually creates no issues, and the SDK still works fine, when there is a disconnection there are exceptions like: 

```
java.lang.AbstractMethodError: Receiver class com.sportradar.unifiedodds.sdk.impl.RecoveryManagerImpl does not define or inherit an implementation of the resolved method abstract handleRecoveryStarted(Lcom/rabbitmq/client/Recoverable;)V
of interface com.rabbitmq.client.RecoveryListener.
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.notifyRecoveryListenersStarted(AutorecoveringChannel.java:828)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.automaticallyRecover(AutorecoveringChannel.java:779)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverChannels(AutorecoveringConnection.java:629)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:575)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$addAutomaticRecoveryListener$3(AutorecoveringConnection.java:509)
        at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:817)
        at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:794)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:678)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Which mean that the `RecoveryManagerImpl` needs to implement an additional missing method.

**Comment by dhrovat** [comment]
Hi,
yes, we are aware of potential problems with old dependent libraries. Also for some customers upgrading them would introduce breaking change.
Good news is that we have plan to provide new version of sdk in January which will include also all libraries upgraded.
