### ISSUE TITLE
Sometimes Radar's client is not able to reconnect after connection loss to RabbitMQ

### ISSUE THREAD

**Issue by thormoz** [sportradar/UnifiedOddsSdkJava#20]
When there is a connection issue and Radar's client send PDOWN messages and starts doing attempts to recover the connection.

Sometimes it is needed to restart the client in order to reconnect. It is not doing it automatically, it gets stuck.

**LOSSING CONNECTION:**
2021-10-31 16:24:52,302 [WARN ] [AMQP Connection 91.201.213.246:5671] [c.r.c.i.ForgivingExceptionHandler] - An unexpected connection driver error occured (Exception message: Connection reset)
2021-10-31 16:24:52,303 [INFO ] [AMQP Connection 91.201.213.246:5671] [c.e.d.f.p.r.service.RadarService] - [CONN]
2021-10-31 16:25:02,004 [ERROR] [AMQP Connection 91.201.213.246:5671] [c.r.c.i.ForgivingExceptionHandler] - Caught an exception when recovering channel 1
java.lang.AbstractMethodError: Receiver class com.sportradar.unifiedodds.sdk.impl.RecoveryManagerImpl does not define or inherit an implementation of the resolved method 'abstract void handleRecoveryStarted(com.rabbitmq.client.Recoverable)' of interface com.rabbitmq.client.RecoveryListener.
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.notifyRecoveryListenersStarted(AutorecoveringChannel.java:819)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.automaticallyRecover(AutorecoveringChannel.java:770)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverChannels(AutorecoveringConnection.java:629)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:575)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$addAutomaticRecoveryListener$3(AutorecoveringConnection.java:509)
        at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:750)
        at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:727)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:611)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-10-31 16:25:02,058 [ERROR] [AMQP Connection 91.201.213.246:5671] [c.r.c.i.ForgivingExceptionHandler] - Caught an exception when recovering channel 2
java.lang.AbstractMethodError: Receiver class com.sportradar.unifiedodds.sdk.impl.RecoveryManagerImpl does not define or inherit an implementation of the resolved method 'abstract void handleRecoveryStarted(com.rabbitmq.client.Recoverable)' of interface com.rabbitmq.client.RecoveryListener.
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.notifyRecoveryListenersStarted(AutorecoveringChannel.java:819)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.automaticallyRecover(AutorecoveringChannel.java:770)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverChannels(AutorecoveringConnection.java:629)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:575)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$addAutomaticRecoveryListener$3(AutorecoveringConnection.java:509)
        at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:750)
        at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:727)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:611)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-10-31 16:25:19,121 [INFO ] [uf-sdk-29967-1-rm-t-0] [c.e.d.f.p.r.service.RadarService] - [PDOWN][1]

**RECOVERY EXCEPTION:**
2021-11-02 10:32:09,785 [ERROR] [AMQP Connection 91.201.213.246:5671] [c.r.c.i.ForgivingExceptionHandler] - Caught an exception when recovering topology Caught an exception while recovering binding between unifiedfeed and amq.gen-GC4A6ZGWXXVts60d_Qxd3g: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering binding between unifiedfeed and amq.gen-GC4A6ZGWXXVts60d_Qxd3g: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverBinding(AutorecoveringConnection.java:775)
at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverTopology(AutorecoveringConnection.java:668)
at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:579)
at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$addAutomaticRecoveryListener$3(AutorecoveringConnection.java:509)
at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:750)
at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:727)
at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:611)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:258)
at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:341)
at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:282)
at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
at com.rabbitmq.client.impl.ChannelN.queueBind(ChannelN.java:1077)
at com.rabbitmq.client.impl.ChannelN.queueBind(ChannelN.java:52)
at com.rabbitmq.client.impl.recovery.RecordedQueueBinding.recover(RecordedQueueBinding.java:30)
at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$recoverBinding$6(AutorecoveringConnection.java:764)
at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.wrapRetryIfNecessary(AutorecoveringConnection.java:818)
at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverBinding(AutorecoveringConnection.java:763)
... 7 common frames omitted

**Comment by dhrovat** [comment]
Hi,
this is a known issue, which was addresses in last version. Also several others improvements were made in regard to connection handling and recovery process. Released in v2.0.51.
